# Copy this file to application-local.properties

spring.datasource.password=YOUR_PASSWORD

# Uncomment if your local environment uses non-default ports:
# spring.datasource.url=jdbc:postgresql://localhost:5433/temperature
# server.port=8088