spring.application.name=temperature-monitor
spring.datasource.url=jdbc:postgresql://localhost:5433/temperature
spring.datasource.username=postgres

# Local development:
# Set the PostgreSQL password in application-local.properties

server.port=8088