CREATE TABLE temperature_measurements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temperature DECIMAL(6, 2) NOT NULL,
    unit VARCHAR(10) NOT NULL
        CONSTRAINT temperature_measurements_unit_check
        CHECK (unit IN ('CELSIUS', 'FAHRENHEIT')),
    measured_at TIMESTAMP WITH TIME ZONE NOT NULL,
    sensor_id VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT temperature_measurements_sensor_measured_at_unique
        UNIQUE (sensor_id, measured_at)
);